serviceType: "LoadBalancer"
service:
  loadBalancerIP: 192.168.50.253

replicaCount: 2

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

prometheus:
  service:
    enabled: true
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9153"
    selector: {}
  monitor:
    enabled: false
    additionalLabels: {}
    namespace: ""
    interval: ""
    selector: {}

servers:
  - zones:
      - zone: home.arpa
        use_tcp: true
    port: 53
    plugins:
      - name: log
      - name: forward
        parameters: . 192.168.50.1
      - name: errors
  - zones:
      - zone: internal
        use_tcp: true
    port: 53
    plugins:
      - name: hosts
        configBlock: |-
          192.168.50.254 homelab.internal
          192.168.50.254 jellyfin.internal
          fallthrough
      - name: errors
  - zones:
      - zone: .
        use_tcp: true
    port: 53
    plugins:
      - name: log
      - name: forward
        parameters: . 1.1.1.1
      - name: errors
      # Serves a /health endpoint on :8080, required for livenessProbe
      - name: health
        configBlock: |-
          lameduck 5s
      # Serves a /ready endpoint on :8181, required for readinessProbe
      - name: ready
      # Serves a /metrics endpoint on :9153, required for serviceMonitor
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
