config:
  kubernetes:context: dreadnought

  k8s:core:
    installGatewayApiCrds: true
    metallb:
      install: true
      addressPool:
        - 192.168.50.253-192.168.50.254

  k8s:helm:
    - releaseName: istio-base
      chart: base
      namespace: istio-system
      repo: "https://istio-release.storage.googleapis.com/charts"
      version: 1.29.1

    - releaseName: istiod
      chart: istiod
      namespace: istio-system
      repo: "https://istio-release.storage.googleapis.com/charts"
      version: 1.29.1

    - releaseName: istio-cni
      chart: cni
      namespace: istio-system
      repo: "https://istio-release.storage.googleapis.com/charts"
      version: 1.29.1

    - releaseName: ztunnel
      chart: ztunnel
      namespace: istio-system
      repo: "https://istio-release.storage.googleapis.com/charts"
      version: 1.29.1

    - releaseName: kiali-operator
      chart: kiali-operator
      namespace: kiali-operator
      repo: "https://kiali.org/helm-charts"
      version: 2.23.0

    - releaseName: headlamp
      chart: headlamp
      namespace: headlamp
      repo: "https://kubernetes-sigs.github.io/headlamp"
      version: 0.41.0
