config:
  kubernetes:context: dreadnought

  k8s:networking:
    installGatewayApiCrds: true
    metallb:
      install: true
      addressPool:
        - 192.168.50.253-192.168.50.254

  k8s:helm:
    - releaseName: coredns-external
      chart: coredns
      namespace: coredns
      repo: "https://coredns.github.io/helm"
      version: "1.45.2"

    - releaseName: headlamp
      chart: headlamp
      namespace: headlamp
      repo: "https://kubernetes-sigs.github.io/headlamp"
      version: 0.41.0

    - releaseName: metrics-server
      chart: metrics-server
      namespace: kube-system
      repo: "https://kubernetes-sigs.github.io/metrics-server"
      version: 3.13.0
